package com.model.common;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 27 22:37:41 EEST 2017
// ---------------------------------------------------------------------
public interface EmployeesViewRow extends Row {
    Integer getEmployeeId();

    void setEmployeeId(Integer value);

    String getFirstName();

    void setFirstName(String value);

    String getLastName();

    void setLastName(String value);

    String getEmail();

    void setEmail(String value);

    String getPhoneNumber();

    void setPhoneNumber(String value);

    Timestamp getHireDate();

    void setHireDate(Timestamp value);

    String getJobId();

    void setJobId(String value);

    BigDecimal getSalary();

    void setSalary(BigDecimal value);

    BigDecimal getCommissionPct();

    void setCommissionPct(BigDecimal value);

    Integer getManagerId();

    void setManagerId(Integer value);

    Integer getDepartmentId();

    void setDepartmentId(Integer value);
}

