package com.model;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 15 10:50:00 EEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HightlyPaidEmpoyeesImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HightlyPaidEmpoyeesImpl() {
    }
}

