package com.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 15 11:42:30 EEST 2017
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void deleteAllEmployees();
}

